version: "3"
services:
  backend:
    image: backend
    build: .
    ports:
      - 8000-8999:8080
    networks:
      - airport-mysql
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: mysql
    platform: linux/x86_64
    networks:
      - airport-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=airport
    ports:
      - 3307:3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=root

networks:
  airport-mysql: