#version: '3'
#
#services:
#  mysql-standalone-container:
#    image: mysql:5.7
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=airport
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=root
#    volumes:
#      - /data/mysql
#      -
#  springboot-container:
#    image: airportRestfulApi-0.0.1-SNAPSHOT:1
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    depends_on:
#      - mysql-standalone-container
#    volumes:
#      - /data/airportRestfulApi-0.0.1-SNAPSHOT

#version: "3.8"
#
#services:
#  mysqldb:
#    image: mysql:5.7
#    restart: unless-stopped
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=airport
#    ports:
#      - 3307:3306
#    volumes:
#      - db:/var/lib/mysql
#  app:
#    depends_on:
#      - mysqldb
#    build: .
#    restart: on-failure
#    env_file: ./.env
#    ports:
#      - 6868:8080
#    environment:
#      SPRING_APPLICATION_JSON: '{
#        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/airport?createDatabaseIfNotExist=true&useSSL=false",
#        "spring.datasource.username" : "root",
#        "spring.datasource.password" : "root",
#        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect"
#      }'
#    volumes:
#      - .m2:/root/.m2
#    stdin_open: true
#    tty: true
#
#volumes:
#  db:
version: '3.9'

services:
  mysql:
    container_name: lab_mysql
    image: mysql
    ports:
      - 3307:3307
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_DATABASE=airport